'use strict';

const region_list = [

[null,0,14,
[ 0,  8,"jp/jp","いしば王国","Wa","@","いしば王国","Wa","@",3140,545,0],
[ 8,  9,"jp/genji","いしば共和国","Wa","@","いしば共和国","Wa","@",3140,545,0],
[ 9,  14,"jp/genji","いしば防衛軍","Wa","@","いしば防衛軍","Wa","@",3200,505,1],
["裏キング","General Headquarters","@"],
[  0,  6,"m","アイアンゴーレムに助けられたクソ村人","Masaru","@"],
["裏の大統領","General Headquarters","@"],
[  6,  7,"m","ひでよおし","Masaru","@"],
["王","King","@"],
[  0,  5,"jp/emp-masaru","まさる天皇","Masaru","@"],
["大統領","King","@"],
[  5,  6,"0","まさる（弟）","Masaru","@"],
[  6,  7,"0","まさる（妹）","Masaru","@"],
["大統領(権限代行)","Prime Minister","@"],
[ 7, 14,"m","失敗まみれ君","Itou Hirobumi","@"],
["（マサルの死刑執行）","King","@"],
[  8,  9,"jp/emp-masaru2","まさる","Masaru","@"],
["首相","Prime Minister","@"],
[ 0, 1,"m","伊藤博文","Itou Hirobumi","@"],
[ 1, 2,"m","失敗まみれ君","Itou Hirobumi","@"],
[ 2, 3,"m","伊藤博文","Itou Hirobumi","@"],
[ 3, 4,"jp/hudson","ジョンハーンハドソン","Itou Hirobumi","@"],
["国務院大臣","Prime Minister","@"],
[ 4, 7,"m","伊藤博文","Itou Hirobumi","@"],
],
[null,9,200,
[ 9,  14,"jp/jp2","いしばロイヤリスト軍","Wa","@","いしばロイヤリスト軍","Wa","@",3155,557,1],
[ 14, 50,"jp/jp2","第2次いしば王国","Wa","@","第2次いしば王国","Wa","@",3155,557,1],
[ 50, 187,"jp/jp2","第3次いしば王国","Wa","@","第3次いしば王国","Wa","@",3155,557,1],
[ 187, 200,"jp/jp2","第4次いしば王国","Wa","@",3155,557,0],
[ 200, 345,"jp/jp2","いしば帝国","Wa","@",3155,557,0],


["王","Prime Minister","@"],
[ 9, 14,"jp/hudson2","ジョンハーンハドソン","Itou Hirobumi","@"],
["(事実上の権力者)","Prime Minister","@"],
[ 14, 17,"0","マサル弟","Itou Hirobumi","@"],
["王","Prime Minister","@"],
[ 17, 48,"jp/hudson2","ジョンソーンハドソン","Itou Hirobumi","@"],
[ 48, 89,"0","ジョンソーンハドソン2世","Itou Hirobumi","@"],
[ 89, 180,"m","ムギ","Itou Hirobumi","@"],
["(対立)","Prime Minister","@"],
[ 123, 180,"0","キリスト様だった野郎君","Itou Hirobumi","@"],
["王","Prime Minister","@"],
[ 180, 200,"0","キリスト様だった野郎君","Itou Hirobumi","@"],

["首相","Prime Minister","@"],
[ 9, 15,"m","伊藤博文","Itou Hirobumi","@"],
[ 15, 29,"m","ホ・ジョン","Itou Hirobumi","@"],
[ 29, 48,"0","川谷大毅","Itou Hirobumi","@"],
[ 48, 50,"0","(首相制度廃止)","Itou Hirobumi","@"],
["ハドソン内閣(首相)","Prime Minister","@"],
[ 50, 67,"jp/hudson","ジョンソーンハドソン","Itou Hirobumi","@"],
[ 67, 100,"jp/hudson3","ジョンソーンハドソン","Itou Hirobumi","@"],
["失敗(ジュニア)内閣(首相)","Prime Minister","@"],
[ 100, 200,"m","失敗まみれジュニア","Itou Hirobumi","@"],
["首相","Prime Minister","@"],
[ 200, 202,"m","ホ・ジョン(臨時)","Itou Hirobumi","@"],
[ 202, 289,"m","イェ・ゥィュハ","Itou Hirobumi","@"],

["ハドソン内閣(外務大臣)","Prime Minister","@"],
[ 50, 100,"m","マン・アルク・アイン・ベルフ","Itou Hirobumi","@"],
["失敗(ジュニア)内閣(外務大臣)","Prime Minister","@"],
[ 100, 143,"jp/hudson3","ジョンソーンハドソン","Itou Hirobumi","@"],
[ 143, 144,"m","ホ・ジョン","Itou Hirobumi","@"],
[ 144, 200,"0","川谷大毅","Itou Hirobumi","@"],
["ハドソン内閣(法務大臣)","Prime Minister","@"],
[ 50, 100,"m","ファサール999世","Itou Hirobumi","@"],
["失敗(ジュニア)内閣(法務大臣)","Prime Minister","@"],
[ 100, 200,"m","失敗まみれくん","Itou Hirobumi","@"],
["ハドソン内閣(LINE大臣)","Prime Minister","@"],
[ 50, 65,"m","失敗まみれくん","Itou Hirobumi","@"],
[ 65, 100,"0","江藤まく","Itou Hirobumi","@"],
["失敗(ジュニア)内閣(LINE大臣)","Prime Minister","@"],
[ 100, 200,"m","ホ・ジョン","Itou Hirobumi","@"],


],
[null, 0, 32,
[  0,  32,null,"ハヤト政権下の九州","(Hayato Rebellion)","(隼人之亂)","ハヤト政権","(Hayato)","(隼人之亂)",3105,584,1],
["(事実上の権力者)","Prime Minister","@"],
[ 0, 32,"m","ヤバ・ハヤト","Itou Hirobumi","@"],
],
[null, 0, 32,
[ 0, 21,"cn/empire","チャイナ国民連合","Nationalist Goverment of Nanjing","@","国民政府","Kuomintang","@",2980,600,0],
["連合指導者","Prime Minister","@"],
[ 0, 21,"0","ピョン君","Itou Hirobumi","@"],

]
];